# Generated by Django 5.0.14 on 2026-08-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Sede')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha de Apertura')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
    ]
