# Generated by Django 5.0.14 on 2026-08-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='ID de Usuario')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo / Puesto')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('fecha_contratacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Contratación')),
            ],
        ),
    ]
