# Generated by Django 5.0.14 on 2026-08-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombre_empleado',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre de Empleado'),
        ),
    ]
